(function(){


var ideaGroupNames = {
    "administrative_ideas": "Administrative",
    "innovativeness_ideas": "Innovativeness",
    "religious_ideas": "Religious",
    "spy_ideas": "Espionage",
    "dynasty0": "Dynastic",
    "influence_ideas": "Influence",
    "offensive_ideas": "Offensive",
    "defensive_ideas": "Defensive",
    "trade_ideas": "Trade",
    "economic_ideas": "Economic",
    "exploration_ideas": "Exploration",
    "maritime_ideas": "Maritime",
    "quality_ideas": "Quality",
    "quantity_ideas": "Quantity",
    "expansion_ideas": "Expansion",
    "humanist_ideas": "Humanist",
    "katholisch0": "Catholic",
    "protestant0": "Protestant",
    "reformiert0": "Reformed",
    "orthodox0": "Orthodox",
    "islam0": "Sunni",
    "tengri0": "Tengri",
    "hindu0": "Hindu",
    "confuci0": "Confucian",
    "budda0": "Buddhist",
    "norse0": "Norse",
    "shinto0": "Shinto",
    "cathar0": "Cathar",
    "coptic0": "Coptic",
    "romuva0": "Romuva",
    "suomi0": "Suomi",
    "jew0": "Jewish",
    "slav0": "Slav",
    "helle0": "Hellanistic",
    "mane0": "Manichean",
    "animist0": "Animist",
    "feti0": "Fetishist",
    "zoro0": "Zoroastrianism",
    "ancli0": "Anglican",
    "nahu0": "Nahuatl",
    "mesoam0": "Mesoamerican",
    "inti0": "Inti",
    "tote0": "Totemism",
    "shia0": "Shia",
    "ibadi0": "Ibadi",
    "hussite0": "Hussite",
    "justiz0": "Judicial",
    "entwicklung0": "Development",
    "gesundheit0": "Health",
    "monarchie0": "Monarchy",
    "republik0": "Republic",
    "aristo0": "Theocracy",
    "diktatur0": "Dictatorship",
    "horde0": "Horde",
    "gross0": "Heavy ship",
    "galle0": "Galley",
    "handel0": "Light ship",
    "kolonialimperium0": "Colonial empire",
    "assimilation0": "Assimilation",
    "gesellschaft0": "Society",
    "propaganda0": "Propaganda",
    "flottenbasis0": "Fleet base",
    "nationalismus0": "Nationalism",
    "konigreich0": "Imperial ambition",
    "imperialismus0": "Imperial",
    "generalstab0": "General staff",
    "stehendesheer0": "Standing army",
    "soldnerheer0": "Mercenary army",
    "wehrpflicht0": "Conscription",
    "waffenqualitat0": "Weapon quality",
    "festung0": "Fortress",
    "kriegsproduktion0": "War production",
    "staatsverwaltung0": "State administration",
    "zentra0": "Centralism",
    "dezentra0": "Decentralism",
    "formation0": "Tactics",
    "militarismus0": "Militarism",
    "shock0": "Shock",
    "fire0": "Fire",
}

var bonusNames = {
    "add_building": "Add building",
    "development_cost_over_25": "Devepment cost for provinces over 25 dev",
    "add_age_forcelimit_naval": "Add naval force limit per age",
    "add_age_authority": "Add mandate/IA per age",
    "extra_navytradition_heavy_ships": "Extra navy tradition from heavy ships",
    "extra_navytradition_galley": "Extra navy tradition from galleys",
    "extra_navytradition_light_ships": "Extra navy tradition from light ships",
    "reduced_dev_malus": "Reduced dev cost malus from nation size",
    "free_cardinal": "Cardinal",
    "build_cost_in_subject_nation": "Build cost in subject nation",
    "stand_interaktion": "Estate interaction",
  "add_age_manpower": "Manpower per age",
  "add_age_sailors": "Sailors per age",
  "add_cb": "Add CB",
  "adm_tech_cost_modifier" : "Admin tech cost modifier",
  "admiral_cost": "Admiral cost",
  "advisor_cost": "Advisor cost",
  "advisor_pool": "Possible advisors",
  "ae_impact": "Aggressive expansion impact",
  "allowed_marine_fraction": "Marine fraction",
  "army_tradition": "Yearly army tradition",
  "army_tradition_decay": "Yearly army tradition decay",
  "artillery_bonus_vs_fort": "Artillery bonus vs fort",
  "artillery_cost": "Artillery cost",
  "artillery_power": "Artillery combat ability",
  "autonomy_change_time": "Autonomy change cooldown",
  "backrow_artillery_damage": "Backrow artillery damage",
  "blockade_efficiency": "Blockade efficiency",
  "build_cost": "Construction cost",
  "build_time": "Construction time",
  "can_fabricate_for_vassals": "May fabricate claims for subjects",
  "caravan_power": "Caravan power",
  "cav_to_inf_ratio": "Cavalry to infantry ratio",
  "cavalry_cost": "Cavalry cost",
  "cavalry_flanking": "Cavalry flanking ability",
  "cavalry_power": "Cavalry combat ability",
  "cb_on_overseas": "CB on overseas",
  "cb_on_primitives": "CB on primitives",
  "cb_on_religious_enemies": "CB on religious enemies",
  "church_power_modifier": "Church power modifier",
  "claim_duration": "Claim duration",
  "colonist_placement_chance": "Settler chance",
  "colonists": "Colonists",
  "core_creation": "Core creation cost",
  "culture_conversion_cost": "Culture conversion cost",
  "decision": "Decision",
  "defensiveness": "Defensiveness",
  "development_cost": "Development cost",
  "devotion": "Yearly devotion",
  "dip_tech_cost_modifier": "Diplo tech cost modifier",
  "diplomatic_annexation_cost": "Diplomatic annexation cost",
  "diplomatic_reputation": "Diplomatic reputation",
  "diplomatic_upkeep": "Diplomatic relations",
  "diplomats": "Diplomats",
  "discipline": "Discipline",
  "drill_decay_modifier": "Army drill decay modifier",
  "drill_gain_modifier": "Army drill gain modifier",
  "embargo_efficiency": "Embargo efficiency",
  "elective_monarchy_dip_buff": "Elective monarchy diplomatic buff",
  "embracement_cost": "Institution embracement cost",
  "enemy_core_creation": "Enemy core creation cost",
  "enforce_religion_cost": "Enforce religion cost",
  "expel_minorities_cost": "Expel minorities cost",
  "extra_manpower_at_religious_war": "Extra manpower at religious war",
  "female_advisor_chance": "Female advisor chance",
  "fire_damage": "Fire damage",
  "fire_damage_received": "Fire damage received",
  "fort_maintenance_modifier": "Fort maintenance modifier",
  "free_leader_pool": "Leader(s) without upkeep",
  "galley_cost": "Galley cost",
  "galley_power": "Galley combat ability",
  "garrison_size": "Garrison size",
  "global_autonomy": "Autonomy modifier",
  "global_colonial_growth": "Global settler increase",
  "global_foreign_trade_power": "Trade power abroad",
  "global_garrison_growth": "Global garrison growth",
  "global_heretic_missionary_strength": "Missionary strength vs heretics",
  "global_institution_spread": "Global institution spread",
  "global_institution_growth": "Global institution growth",
  "global_manpower": "National manpower",
  "global_manpower_modifier": "National manpower modifier",
  "global_missionary_strength": "Missionary strength",
  "global_prov_trade_power_modifier": "Provincial trade power modifier",
  "global_regiment_cost": "Regiment cost",
  "global_regiment_recruit_speed": "Regiment recruit speed",
  "global_religious_conversion_resistance": "Religious conversion resistance",
  "global_sailors": "National sailors",
  "global_sailors_modifier": "National sailors modifier",
  "global_ship_cost": "Ship costs",
  "global_ship_recruit_speed": "Shipbuilding time",
  "global_ship_repair": "Global ship repair",
  "global_ship_trade_power": "Ship trade power",
  "global_spy_defence": "Foreign spy detection",
  "global_supply_limit_modifier": "Global supply limit modifier",
  "global_tariffs": "Tariffs",
  "global_tax_modifier": "National tax modifier",
  "global_trade_goods_size_modifier": "Goods produced modifier",
  "global_trade_power": "Global trade power",
  "global_unrest": "National unrest",
  "governing_capacity": "Governing capacity",
  "governing_capacity_modifier": "Governing capacity modifier",
  "harmonization_speed": "Religious harmonization speed",
  "harsh_treatment_cost": "Harsh treatment cost",
  "heavy_ship_cost": "Heavy ship cost",
  "heavy_ship_power": "Heavy ship combat ability",
  "heir_chance": "Chance of new heir",
  "horde_unity": "Yearly horde unity",
  "hostile_attrition": "Hostile attrition",
  "idea_cost":"Idea cost",
  "imperial_authority": "Imperial authority growth modifier",
  "imperial_authority_value": "Imperial authority",
  "imperial_mandate": "Mandate",
  "improve_relation_modifier": "Improve relations modifier",
  "infantry_cost": "Infantry cost",
  "infantry_power": "Infantry combat ability",
  "inflation_action_cost": "Reduce inflation cost reduction",
  "inflation_reduction": "Yearly inflation reduction",
  "inflationreduction": "Yearly inflation reduction",
  "innovativeness_gain": "Innovativeness gain",
  "institution_spread_from_true_faith": "Institution spread from true faith",
  "interest": "Interest",
  "land_attrition": "Land attrition",
  "land_forcelimit": "Land force limit",
  "land_forcelimit_modifier": "Land force limit modifier",
  "land_maintenance_modifier": "Land maintenance modifier",
  "land_morale": "Morale of armies",
  "leader_land_fire": "Land leader fire",
  "leader_land_manuever": "Land leader maneuver",
  "leader_land_shock": "Land leader shock",
  "leader_naval_fire": "Naval leader fire",
  "leader_naval_manuever": "Naval leader maneuver",
  "leader_naval_shock": "Naval leader shock",
  "leader_siege": "Leader siege",
  "legitimacy": "Yearly legitimacy",
  "liberty_desire_from_subject_development": "Liberty desire from subjects development",
  "light_ship_cost": "Light ship cost",
  "light_ship_power": "Light ship combat ability",
  "loot_amount": "Loot amount",
  "manpower_in_true_faith_provinces": "Manpower in true faith provinces",
  "manpower_recovery_speed": "Manpower recovery speed",
  "max_absolutism": "Maximum absolutism",
  "may_explore": "May explore",
  "may_perform_slave_raid": "May raid coasts",
  "merc_maintenance_modifier": "Mercenary maintenance",
  "mercenary_cost":"Mercenary cost",
  "mercenary_discipline":"Mercenary discipline",
  "mercenary_manpower":"Mercenary manpower",
  "merchants":"Merchants",
  "meritocracy":"Yearly meritocracy",
  "mil_tech_cost_modifier":"Military tech cost modifier",
  "missionaries":"Missionaries",
  "missionary_maintenance_cost":"Missionary maintenance cost",
  "monarch_admin_power":"Monarch administrative skill",
  "monarch_diplomatic_power":"Monarch diplomatic skill",
  "monarch_military_power":"Monarch military skill",
  "monthly_fervor_increase":"Monthly fervor increase",
  "monthly_militarized_society":"Monthly militarized society",
  "monthly_splendor":"Monthly splendor",
  "movement_speed":"Movement speed",
  "naval_attrition":"Naval attrition",
  "naval_forcelimit":"Naval force limit",
  "naval_forcelimit_modifier":"Naval force limit modifier",
  "naval_maintenance_modifier":"Naval maintenance modifier",
  "naval_morale":"Morale of navies",
  "navy_tradition":"Yearly navy tradition",
  "navy_tradition_decay":"Yearly navy tradition decay",
  "num_accepted_cultures":"Number of accepted cultures",
  "papal_influence":"Yearly papal influence",
  "prestige":"Yearly prestige",
  "prestige_decay":"Prestige decay",
  "prestige_from_land":"Prestige from land battles",
  "privateer_efficiency":"Privateer efficiency",
  "production_efficiency":"Production efficiency",
  "promote_culture_cost": "Promote culture cost",
  "province_warscore_cost": "Province war score cost",
  "range": "Colonial range",
  "raze_power_gain": "Razing power gain",
  "rebel_support_efficiency":"Rebel support efficiency",
  "recover_army_morale_speed":"Recover army morale speed",
  "recover_navy_morale_speed": "Recover navy morale speed",
  "reduced_liberty_desire": "Liberty desire in subjects",
  "reduced_stab_impacts": "Reduced stability impact from diplo",
  "reform_progress_growth": "Reform progress growth",
  "reinforce_cost_modifier":"Reinforce cost modifier",
  "reinforce_speed":"Reinforce speed",
  "relation_with_heretics":"Relation with heretics",
  "religious_unity": "Religious unity",
  "republican_tradition": "Yearly republican tradition",
  "sailor_maintenance_modifer": "Sailor maintenance modifier",
  "sailors_recovery_speed": "Sailor recovery speed",
  "same_culture_advisor_cost": "Cost of advisors with ruler's culture",
  "ship_durability":"Ship durability",
  "shock_damage":"Shock damage",
  "shock_damage_received":"Shock damage received",
  "siege_ability":"Siege ability",
  "siege_blockade_progress":"Siege blockade progress",
  "special_unit_forcelimit":"Special unit force limit",
  "spy_offence":"Spy network construction",
  "stability_cost_modifier": "Stability cost modifier",
  "state_maintenance_modifier":"State maintenance modifier",
  "technology_cost":"Technology cost",
  "tolerance_heathen":"Tolerance of heathens",
  "tolerance_heretic":"Tolerance of heretics",
  "tolerance_own":"Tolerance of true faith",
  "trade_company_governing_cost":"Trade company governing cost",
  "trade_efficiency":"Trade efficiency",
  "trade_range_modifier":"Trade range modifier",
  "trade_steering":"Trade steering",
  "transport_cost":"Transport cost",
  "transport_power":"Transport combat ability",
  "unjustified_demands":"Unjustified demands",
  "war_exhaustion":"War exhaustion",
  "war_exhaustion_cost": "War exhaustion cost",
  "war_taxes_cost_modifier":"War taxes cost",
  "warscore_cost_vs_other_religion": "War score cost vs other religions",
  "yearly_absolutism":"Yearly absolutism",
  "yearly_army_professionalism":"Yearly army professionalism",
  "yearly_corruption":"Yearly corruption",
  "yearly_harmony":"Yearly harmony increase",
  "yearly_patriarch_authority":"Yearly patriarch authority",
  "years_of_nationalism":"Years of separatism",
  "morale_bonus_5_cultures": "Morale bonus from 5 cultures",
  "build_cost_in_colo_nation": "Build cost in colonial nation",
  "no_prof_loss_for_mercs": "No professionalism loss from mercs",
}

var miscNames = {
    "age_of_discovery": "Age of discovery",
    "age_of_reformation": "Age of reformation",
    "age_of_absolutism": "Age of absolutism",
    "age_of_revolutions": "Age of revolutions",
    "cb_dynastie": "Dynastic CB",
    "diktatur_dec": "Dictator decision",
    "cb_coast": "Coastal CB",
    "navalbase_lvl_1": "Level 1 naval base",
    "navalbase_lvl_2": "Level 2 naval base",
    "fortress_keep": "Fortress keep",
    "fortress_barracks": "Fortress barracks",
    "fortress_towers": "Fortress towers",
    "fortress_artillery": "Fortress artillery",
    "fortress_wall": "Fortress wall",
    "fortress_supply": "Fortress supply",
    "navyforcelimit_lvl_2": "Lvl 2 naval force limit",
    "navyforcelimit_lvl_3": "Lvl 3 naval force limit",
    "navymanpower_lvl_2": "Lvl 2 sailors",
    "navymanpower_lvl_3": "Lvl 3 sailors",
}

window.replaceName = function(s){
    if(ideaGroupNames[s]){
        return ideaGroupNames[s];
    }
    if(bonusNames[s]){
        return bonusNames[s];
    }
    if(miscNames[s]){
        return miscNames[s];
    }
    return s;
}

window.formatDisplay = function(bonusName, bonusVal){
    // should be thousand formatted
    if(["National manpower", "Manpower per age"].indexOf(bonusName) > -1){
        return bonusVal * 1000;
    }

    // Has decimal place but shouldnt be percentaged
    if(["Mandate", "Interest", "Yearly inflation reduction", "Tolerance of true faith", "Yearly devotion", "Yearly legitimacy", "Yearly republican tradition","Yearly horde unity", "Army tradition", "Global institution growth"].indexOf(bonusName) !== -1){
        return parseFloat(bonusVal).toFixed(2);
    }
    if(["Yearly absolutism", "War exhaustion"].indexOf(bonusName) !== -1){
        return bonusVal;
    }
    // Has decimal place or otherwise SHOULD be percentaged
    if(bonusVal.indexOf('.') > -1 || [].indexOf(bonusName) !== -1){
        var suffix = '';
        if(bonusVal.indexOf('/') > -1){
            var split = bonusVal.split('/');
            suffix = '/'+split[1];
            bonusVal = split[0];
        }
        var valNum = parseFloat(bonusVal);
        var percentNum = valNum * 100;
        if(Number.isInteger(percentNum)){
            return `${(valNum * 100).toFixed(0)}%${suffix}`;
        }
        return `${(valNum * 100).toFixed(1)}%${suffix}`;
    }
    return bonusVal;
}
}())